name: Java CI with Maven vizhu

on:
  push:
    branches: [ develop-2 ]
  pull_request:
    branches: [ develop-2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp-jars
          path: target/*.jar
